/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  premiereSidebar: [{ type: 'autogenerated', dirName: 'nsi-1ere' }],
  sntSidebar: [{ type: 'autogenerated', dirName: 'snt' }],
  termSidebar: [{ type: 'autogenerated', dirName: 'nsi-term' }],
  mathsSidebar: [{ type: 'autogenerated', dirName: 'maths' }],
  diversSidebar: [{ type: 'autogenerated', dirName: 'divers' }],
  annalesSidebar: [{ type: 'autogenerated', dirName: 'annales' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
}

module.exports = sidebars
